Induk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('tax.urls', namespace = "tax")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^learning/', include('learning.urls', namespace="learning")),
    url(r'^report/', include('report.urls', namespace="report")),
    url(r'', include('notice.urls', namespace="notice")),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    # url(r'^accounts/register/$', UserCreateView.as_view(), name = 'register'),
    # url(r'^accounts/register/done/$', UserCreateDoneTV.as_view, name = 'register_done'),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.learning_list, name = "learning_list"),
    url(r'^(?P<pk>\d+)/$', views.learning_detail, name="learning_detail"),
    url(r'^new/$', views.learning_new, name="learning_new"),
    url(r'^(?P<pk>\d+)/edit/$', views.learning_edit, name="learning_edit"),
    url(r'^(?P<pk>\d+)/del/$', views.learning_del, name="learning_del"),
    url(r'^(?P<pk>\d+)/comment/$', views.learning_comment, name="learning_comment"),
]

learning/models.py
from django.db import models
from django.conf import settings
from model_rename import RenameFile


class Learning(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    files = models.FileField(null=True, blank=True, upload_to=RenameFile('learning/%Y%m%d/'))
    image = models.ImageField(null=True, blank=True, upload_to=RenameFile('learning/%Y%m%d/'))
    show = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '학습자료'
        verbose_name_plural = '학습자료'


class LearningComment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    learning = models.ForeignKey(Learning)
    # comment = models.ForeignKey("self", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.learning.title

    class Meta:
        verbose_name = '학습자료 댓글'
        verbose_name_plural = '학습자료 댓글'

learning/forms.py
from django import forms
from .models import Learning, LearningComment


class LearningForm(forms.ModelForm):
	class Meta:
		model = Learning
		fields = ('title', 'content', 'files', 'image')


class LearningCommentForm(forms.ModelForm):
	class Meta:
		model = LearningComment
		fields = ('message',)

learning/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Learning, LearningComment
from .forms import LearningForm, LearningCommentForm
from Induk.decorators import is_article_active
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# def index(request):
#   return render(request, "learning/index.html")

@login_required
def learning_list(request):
    learning_list = Learning.objects.filter(show=True).order_by("-updated_at")
    paginator = Paginator(learning_list, 10)

    page = request.GET.get('page')

    try:
        learning_list = paginator.page(page)
    except PageNotAnInteger:
        learning_list = paginator.page(1)
    except EmptyPage:
        learning_list = paginator.page(paginator.num_pages)

    return render(request, "learning/learning_list.html", {
        "learning_list": learning_list,
    })


@login_required
@is_article_active
def learning_detail(request, pk):
    learning = get_object_or_404(Learning, pk=pk)
    return render(request, "learning/learning_detail.html", {
        "learning": learning,
        "comments": LearningComment.objects.filter(learning=learning),
        "comment_form": LearningCommentForm(),
    })


def learning_new(request):
    if request.method == "POST":
        form = LearningForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.show = True
            form.save()
            return redirect("learning:learning_detail", form.pk)
    else:
        form = LearningForm()
    return render(request, "learning/learning_form.html", {
        "form": form,
    })


@is_article_active
def learning_edit(request, pk):
    learning = get_object_or_404(Learning, pk=pk)
    if request.method == "POST":
        form = LearningForm(request.POST, instance=learning)
        if form.is_valid():
            form = form.save()
            return redirect("learning:learning_detail", learning.pk)
    else:
        form = LearningForm(instance=learning)
    return render(request, "learning/learning_form.html", {
        "form" : form,
    })


@is_article_active
def learning_del(request, pk):
    try:
        learning = Learning.objects.get(pk=pk)
    except Learning.DoesNotExist:
        return redirect('learning:learning_list')
    learning.show = False
    learning.save()

    return redirect('learning:learning_list')


@is_article_active
def learning_comment(request, pk):
    if request.method == 'POST':
        try:
            learning = Learning.objects.get(pk=pk)
        except Learning.DoesNotExist:
            return redirect('learning:learning_list')
        if not learning.show:
            return redirect('learning:learning_list')
        else:
            form = LearningCommentForm(request.POST)
            if form.is_valid():
                print('form valid')
                comment = form.save(commit=False)
                comment.author = request.user
                comment.learning = learning
                comment.save()
            return render(request, "learning/learning_comment_form.html", {
                "learning": learning,
                "comments": LearningComment.objects.filter(learning=learning),
                "comment_form": LearningCommentForm(),
            })
    return redirect('learning:learning_list')

learning/templates/learning/learning_comment_form.html
{% load customtags %}
<div class="comments__new">
    <form name="comment_new" action="{% url 'learning:learning_comment' pk=learning.pk %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control" name="message" rows="1" placeholder="Write your comment here"></textarea>
        <input type="hidden" id="comments_count" name="comments_count" value="{{ comments.count }}" />
        <button type="submit" id="comments__new" class="comments__new" class="btn btn-primary" value="SAVE">SAVE</button>
    </form>
</div>
<br/>
<div class="comments__list">
    <div class="comments__heading">{{ comments.count }} comments</div>
    <hr/>
    <div class="comments__item">
        {% for comment in comments %}
        <div class="comments-item__body">
            <div class="comments-item__info">
                <div class="comments-item-info__author">
                    {{ comment.author.first_name }}
                </div>
                <div class="comments-item-info__divider"><i class="fa fa-circle"></i></div>
                <div class="comments-item-info__timestamp">{{ comment.created_at|timesince|split:","|first }}전</div>
                <div class="comments-item__content">{{ comment.message }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

learning/templates/learning/learning_detail.html
{% extends 'base4.html' %}
{% load customtags %}
{% load staticfiles %}
{% block css %}
<style>
.title_{
    font-size:20px;
}
.author_{
    color:gray;
}
.time_recorded{
    color:gray;
}
.content_{
    margin-top:40px;
    margin-left:5%;
    margin-right:5%;
    font-size:20px;
}
.edit_del{
    margin-right:5%;
}
.comment_body{
margin:1%;
}
button[type=submit]{
  margin:1%;
  float:right;
  color:white;
  padding:5px 15px;
  background:orange;
  border:0 none;
  cursor:pointer;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
</style>
{% endblock %}

{% block content %}

 <div class="page-topbar">
      <div class="container">
        <div class="row">
          <div class="col-sm-4">

            <h3>학습자료실</h3>

          </div>
          <div class="col-sm-8 hidden-xs">

            <ol class="breadcrumb">
              <li><a href="{% url 'learning:learning_list' %}">Home</a></li>
              <li><a href="{% url 'learning:learning_list' %}"> 리스트 보기 </a></li>
              <li class="active">{{learning.title}}</li>
            </ol>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </div>

<div class = "container">
  <div class="row">
    <div class="col-sm-12">
      <div class="bolg__item">
        <div class="blog__header">
          <h1 class="blog__title">
            {{ learning.title }}
          </h1>
          <ul class="blog__info">
            <li><i class="fa fa-user"></i>&nbsp;{{ learning.author.first_name }}</li>
            <li><i class="fa fa-calendar"></i>&nbsp;{{ learning.created_at}}</li>
            <li><a href="/learning" style="color:white; background-color:orange;" class="btn btn-xs">List</a></li>
            {% if request.user == learning.author %}
              <li><a href="{% url 'learning:learning_edit' learning.pk %}" style="color:white; background-color: orange;" class="btn btn-xs">edit</a></li>
              <li><a href="{% url 'learning:learning_del' learning.pk %}" style="color:white; background-color:orange;" class="btn btn-xs">delete</a></li>
            {% endif %}
          </ul>
        </div>
        <div class="blog__body">
          <p>
            {{ learning.content|linebreaks }}
          </p>
        </div>

         {% if learning.files %}
          files : {{ learning.files.url|split:"/"|last }} <br/>
          <a download="{{learning.files.url}}" href="{{learning.files.url}}">파일 다운로드 받기</a><br>
        {% endif %}

        {% if learning.image %}
          images : <img src="{{ learning.image.url }}" class="img-responsive" style="max-width: 50%"> <br/>
          <a download="{{learning.image.url}}" href="{{learning.image.url}}">이미지 다운로드 받기</a>
        {% endif %}
        <br/><br/>
      </div>
      <div class="comments">
      {% include 'learning/learning_comment_form.html'%}
      </div>
    </div>
  </div>
</div>
<!--
<div class = "container">
    <section class="content">
        <div class="row text-left title_">
            <h1 class = "title_">
            <b> {{ learning.title }}</b>
            </h1>
            <hr width="100%" color="oranges">
        </div>
            <ul class = "text-left info_">

            <i class = "fa fa-user"></i>
                <span class="author_"> 작성자 : {{ learning.author.first_name }}</span>
            <i class = "fa fa-calendar"></i>
                작성일 : <span class="time_recorded">{{ learning.created_at }}</span>
           </ul>
           </section>

    <div class="content_">
        {{ learning.content }} <br/>
    </div>
    {% if learning.files %}
        files : {{ learning.files.url }} <br/>
        <a download="{{learning.files.url}}" href="{{learning.files.url}}">파일 다운로드 받기</a>
    {% endif %}

    {% if learning.image %}
        images : <img src="{{ learning.image.url }}" width="100%" height="50px"> <br/>
        <a download="{{learning.image.url}}" href="{{learning.image.url}}">이미지 다운로드 받기</a>
    {% endif %}
    <br/><br/>

    {% if request.user == learning.author %}
    <div class="row text-left edit_del">
       &nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'learning:learning_edit' learning.pk %}">EDIT</a>&nbsp;&nbsp;
        <a href="{% url 'learning:learning_del' learning.pk %}">DELETE</a>&nbsp;&nbsp;
        <a href=/learning>목록 보기</a>
    </div>
    {% endif %}
</section>

<form name="comment_new" action="{% url 'learning:learning_comment' pk=learning.pk %}" method="POST">
    {% csrf_token %}
    <textarea name="message" rows="3" cols="80"></textarea>
    <input type="submit" value="댓글쓰기">
</form>

<div class="comments">
{% now "SHORT_DATETIME_FORMAT" as time_now %}
    {% for comment in comments %}
        <div class="comment_body">
      <span style="font-size:15pt;">{{comment.message}} </span><span style="color:orange;">by</span> <span style="color:gray;">{{comment.author}}</span><br/><span style="margin-left:2%; color:gray; font-size:8pt;">{{ comment.created_at|timesince }}전</span>
        </div>
    {% endfor %}
</div>
-->
{% endblock %}
{% block javascript %}
<script>
var js_root = "{% static 'js/comment_add.js'%}"
</script>
<script src="{% static 'js/comment_add.js' %}"></script>
{% endblock %}

learning/templates/learning/learning_form.html
{% extends 'base2.html' %}
{% load bootstrap3 %}

{% block content %}
<div class = "container">
<h1 class = "block-header">
<span> 학습자료실 </span>
</h1>
<br>
<br>

<div class = "container">
<div class = "col-sm-12">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">SAVE</button>
</form>
</div>
</div>
</div>
{% endblock %}

learning/templates/learning/learning_list.html
{% extends 'base2.html' %}

{% block content %}

<div class="container">
    <h1 class="block-header">
      <span>학습자료실</span>
    </h1>
    <br>
    <br>
    <br>
      <table class="table">
        <tr>
          <td>글번호</td>
          <td>제목 </td>
          <td>글쓴이</td>
          <td>작성날짜</td>
        </tr>
{% for learning in learning_list %}
        <tr>
          <td>{{learning.pk}}</td>
          <td class="post_title"><a href = '{% url "learning:learning_detail" learning.pk %}'>{{learning.title}}</a></td>
          <td>{{ learning.author.first_name }}</td>
          <td>{{ learning.created_at }}</td>
        </tr>
      {% endfor %}
    </table>
<nav class="text-left">
      <ul class="pagination">
      {% if learning_list.has_previous %}
        <li>
          <a href="?page={{ learning_list.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for page_number in learning_list.paginator.page_range %}
        {% if page_number == learning_list.number %}
          <li class="active"><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% else %}
        <li><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% endif %}
      {%endfor%}
      {% if learning_list.has_next %}
        <li>
          <a href="?page={{ learning_list.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% else %}
        <li class ="disabled">
          <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% endif %}
      </ul>
    </nav>
    <a style="margin-left:10px" href="{% url 'learning:learning_new' %}">새 글쓰기</a>
    <!-- Pagination -->

   </div>
  {% endblock %}