Induk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('tax.urls', namespace = "tax")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^learning/', include('learning.urls', namespace="learning")),
    url(r'^report/', include('report.urls', namespace="report")),
    url(r'', include('notice.urls', namespace="notice")),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    # url(r'^accounts/register/$', UserCreateView.as_view(), name = 'register'),
    # url(r'^accounts/register/done/$', UserCreateDoneTV.as_view, name = 'register_done'),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.report_index, name = 'report_index'),

	url(r'^(?P<company>\w+)/$', views.report_list, name="report_list"),
	url(r'^(?P<company>\w+)/new/$', views.report_new, name="report_new"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/$', views.report_detail, name="report_detail"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/edit/$', views.report_edit, name="report_edit"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/del/$', views.report_del, name="report_del"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/comment/$', views.report_comment, name="report_comment"),
]

report/models.py
from django.db import models
from django.conf import settings
from model_rename import RenameFile


class Board(models.Model):
	company = models.CharField(max_length=20, help_text='url에서 쓰이는 이름', unique=True)
	title = models.CharField(max_length=20, help_text='화면에 보여지는 이름', unique=True)
	order = models.PositiveIntegerField(help_text='화면에 표시되는 순서')
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = '기업 리스트'
		verbose_name_plural = '기업 리스트'


class Report(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	board = models.ForeignKey(Board, related_name='board_set')
	title = models.CharField(max_length=30)
	content = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	files = models.FileField(null=True, blank=True, upload_to=RenameFile('report/%Y%m%d/'))
	image = models.ImageField(null=True, blank=True, upload_to=RenameFile('report/%Y%m%d/'))
	show = models.BooleanField(default=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = '기업보고'
		verbose_name_plural = '기업보고'


class ReportComment(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	message = models.TextField()
	report = models.ForeignKey(Report)
	# comment = models.ForeignKey("self", blank=True, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.report.title

	class Meta:
		verbose_name = '기업보고 댓글'
		verbose_name_plural = '기업보고 댓글'

report/forms.py
from django import forms
from .models import Report, Board, ReportComment


class ReportForm(forms.ModelForm):
	# board = forms.ModelChoiceField(widget=forms.Select(attrs={'size':'13'}), queryset=Board.objects.all())

	class Meta:
		model = Report
		fields = ('title', 'content', 'files', 'image')

class ReportCommentForm(forms.ModelForm):
	class Meta:
		model = ReportComment
		fields = ('message',)

report/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse

from Induk.decorators import is_company_active, is_article_active, is_user_belong_to

from .forms import ReportForm, ReportCommentForm
from .models import Board, Report, ReportComment


def report_index(request):
	user = request.user
	company_list = Board.objects.filter(active=True).filter(user_set=user).order_by('order')
	return render(request, 'report/report_index.html', {
		'company_list': company_list,
	})


@is_company_active
@is_user_belong_to
def report_list(request, company):
	report_list = Report.objects.filter(board__company__exact=company).filter(show=True).order_by('-updated_at')
	title = Board.objects.get(company=company)
	paginator = Paginator(report_list, 10)
	page = request.GET.get('page')

	try:
		report_list = paginator.page(page)
	except PageNotAnInteger:
		report_list = paginator.page(1)
	except EmptyPage:
		report_list = paginator.page(paginator.num_pages)

	return render(request, "report/report_list.html", {
		"report_list": report_list,
		'company': company,
		'title': title,
	})


@is_company_active
@is_article_active
@is_user_belong_to
def report_detail(request, company, pk):
	report = get_object_or_404(Report, pk=pk)
	return render(request, "report/report_detail.html", {
		'company': company,
		"report": report,
		'comments': ReportComment.objects.filter(report=report),
	})


@is_company_active
@is_user_belong_to
def report_new(request, company):
	if request.method == "POST":
		form = ReportForm(request.POST, request.FILES)
		if form.is_valid():
			form = form.save(commit=False)
			form.author = request.user
			form.board = get_object_or_404(Board, company=company)
			form.save()
			return redirect(reverse("report:report_list", args=(company,)))
	else:
		form = ReportForm()
	return render(request, "report/report_form.html", {
		"form": form,
	})


@is_company_active
@is_article_active
@is_user_belong_to
def report_edit(request, company, pk):
	report = get_object_or_404(Report, pk=pk)
	if request.method == "POST":
		form = ReportForm(request.POST, instance=report)
		if form.is_valid():
			form = form.save()
			return redirect(reverse("report:report_detail", args=(company, pk)))
	else:
		form = ReportForm(instance=report)
	return render(request, "report/report_form.html", {
		"form": form,
	})


@is_company_active
@is_article_active
@is_user_belong_to
def report_del(request, company, pk):
	try:
		report = Report.objects.get(pk=pk)
	except Report.DoesNotExist:
		return redirect(reverse("report:report_list", args=(company,)))
	report.show = False
	report.save()

	return redirect(reverse("report:report_list", args=(company,)))


@is_company_active
@is_article_active
@is_user_belong_to
def report_comment(request, company, pk):
	if request.method == 'POST':
		try:
			report = Report.objects.get(pk=pk)
		except Report.DoesNotExist:
			return redirect('report:report_list')
		if not report.show:
			return redirect('report:report_list')
		else:
			form = ReportCommentForm(request.POST)
			if form.is_valid():
				print('form valid')
				comment = form.save(commit=False)
				comment.author = request.user
				comment.report = report
				comment.save()
			# return redirect(reverse("report:report_detail", args=(company, pk)))
			return render(request, "report/report_comment_form.html", {
				"report": report,
				"company": company,
				"comments": ReportComment.objects.filter(report=report),
				"comment_form": ReportCommentForm(),
			})
	return redirect(reverse("report:report_list", args=(company,)))

report/templates/report/report_comment_form.html
{% load customtags %}
<div class="comments__new">
    <form name="comment_new" action="{% url 'report:report_comment' company=company pk=report.pk %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control" name="message" rows="1" placeholder="Write your comment here"></textarea>
        <button type="submit" id="comments__new" class="comments__new" class="btn btn-primary" value="SAVE">SAVE</button>
    </form>
</div>
<br/>
<div class="comments__list">
    <div class="comments__heading">{{ comments.count }} comments</div>
    <hr/> {% for comment in comments %}
    <div class="comments__item">
        <div class="comments--item__body">
            <div class="comments-item__info">
                <div class="comments-item-info__author">
                    {{ comment.author.first_name }}
                </div>
                <div class="comments-item-info__divider"><i class="fa fa-circle"></i></div>
                <div class="comments-item-info__timestamp">{{ comment.created_at|timesince|split:","|first }}전</div>
                <div class="comments-item__content">{{ comment.message }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

report/templates/report/report_detail.html
{% extends 'base4.html' %}
{% load customtags %}
{% load staticfiles %}
{% block css %}
<style>
.title_{
    font-size:20px;
}
.author_{
    color:gray;
}
.time_recorded{
    color:gray;
}
.content_{
    margin-top:40px;
    margin-left:5%;
    margin-right:5%;
    font-size:20px;
}
.edit_del{
    margin-right:5%;
}
.comment_body{
margin:1%;
}
button[type=submit]{
  margin:1%;
  float:right;
  color:white;
  padding:5px 15px;
  background:orange;
  border:0 none;
  cursor:pointer;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
</style>
{% endblock %}

{% block content %}

 <div class="page-topbar">
      <div class="container">
        <div class="row">
          <div class="col-sm-4">

            <h3>공지 사항</h3>

          </div>
          <div class="col-sm-8 hidden-xs">

            <ol class="breadcrumb">
              <li><a href="{% url 'report:report_index' %}">Home</a></li>
              <li><a href="{% url 'report:report_list' company=company %}"> 리스트 보기 </a></li>
              <li class="active">{{report.title}}</li>
            </ol>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </div>
<div class = "container">
  <div class="row">
    <div class="col-sm-12">
      <div class="bolg__item">
        <div class="blog__header">
          <h1 class="blog__title">
            {{ report.title }}
          </h1>
          <ul class="blog__info">
            <li><i class="fa fa-user"></i>&nbsp;{{ report.author.first_name }}</li>
            <li><i class="fa fa-calendar"></i>&nbsp;{{ report.created_at}}</li>
            <li><a href="/report" style="color:white; background-color:orange;" class="btn btn-xs">List</a></li>
            {% if request.user == report.author %}
              <li><a href="{% url 'report:report_edit' company=company pk=report.pk %}" style="color:white; background-color: orange;" class="btn btn-xs">edit</a></li>
              <li><a href="{% url 'report:report_del' company=company pk=report.pk %}" style="color:white; background-color:orange;" class="btn btn-xs">delete</a></li>
            {% endif %}
          </ul>
        </div>
        <div class="blog__body">
          <p>
            {{ report.content|linebreaks }}
          </p>
        </div>

         {% if report.files %}
          files : {{ report.files.url|split:"/"|last }} <br/>
          <a download="{{report.files.url}}" href="{{report.files.url}}">파일 다운로드 받기</a><br>
        {% endif %}

        {% if report.image %}
          images : <img src="{{ report.image.url }}" class="img-responsive" style="max-width: 50%"> <br/>
          <a download="{{report.image.url}}" href="{{report.image.url}}">이미지 다운로드 받기</a>
        {% endif %}
        <br/><br/>
      </div>
      <div class="comments">
        {% include 'report/report_comment_form.html' %}
      </div>
    </div>
  </div>
</div>
<!--
<div class = "container">
    <section class="content">
        <div class="row text-center title_">
            <h1 class = "title_">
            <b> {{ report.title }}</b>
            </h1>
            <hr width="100%" color="oranges">
        </div>
            <ul class = "text-center info_">
            <li>
            <i class = "fa fa-user"></i>
                <span class="author_"> 작성자 : {{ report.author.first_name }}</span>&nbsp&nbsp&nbsp
            <i class = "fa fa-calendar"></i>
                작성일 : <span class="time_recorded">{{ report.created_at }}</span>
           </div>
    <div class="content_">
        {{ report.content }} <br/>
    </div>
    {% if report.files %}
        files : {{ report.files.url }} <br/>
        <a download="{{report.files.url}}" href="{{report.files.url}}">파일 다운로드 받기</a>
    {% endif %}

    {% if report.image %}
        images : <img src="{{ report.image.url }}" width="100%" height="50px"> <br/>
        <a download="{{report.image.url}}" href="{{report.image.url}}">이미지 다운로드 받기</a>
    {% endif %}
    <br/><br/>

    {% if request.user == report.author %}
    <div class="row text-right edit_del">
        <a href="{% url 'report:report_edit' company=company pk=report.pk %}">EDIT</a>&nbsp;&nbsp;
        <a href="{% url 'report:report_del' company=company pk=report.pk %}">DELETE</a>
    </div>
    {% endif %}
</section>

<form name="comment_new" action="{% url 'report:report_comment' company=company pk=report.pk %}" method="POST">
	{% csrf_token %}
	<textarea name="message" rows="8" cols="80"></textarea>
	<input type="submit" value="댓글쓰기">
</form>

<div class="comments">
	{% for comment in comments %}
		  <div class="comment_body">
      <span style="font-size:15pt;">{{comment.message}} </span><span style="color:orange;">by</span> <span style="color:gray;">{{comment.author}}</span><br/><span style="margin-left:2%; color:gray; font-size:8pt;">{{ comment.created_at|timesince }}전</span>
    </div>

	{% endfor %}
</div>
-->

{% endblock %}
{% block javascript %}
<script>
var js_root = "{% static 'js/comment_add.js' %}";
</script>
<script src="{% static 'js/comment_add.js' %}"></script>
{% endblock %}

report/templates/report/report_form.html
{% extends 'base2.html' %}
{% load bootstrap3 %}

{% block content %}
<div class = "container">
<h1 class = "block-header">
<span> 기업보고 </span>
</h1>
<br>
<br>

<div class = "container">
<div class = "col-sm-12">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">SAVE</button>
</form>
</div>
</div>
</div>
{% endblock %}

report/templates/report/report_index.html
{% extends 'base2.html' %}

{% block content %}

<div class="container">
    <h1 class="block-header">
      <span>기업 자료실</span>
    </h1>
    <br>
    <br>
    <br>
      <table class="table">
				{% for company in company_list %}
				{% cycle '<tr>' '' '' '' '' %}
					<td><a href ="{% url 'report:report_list' company=company.company %}">{{company.title}}</a></td>
				{% cycle '' '' '' '' '</tr>' %}
				{% endfor %}
    </table>

   </div>
  {% endblock %}

report/templates/report/report_list.html
{% extends 'base2.html' %}

{% block content %}

<div class="container">
    <h1 class="block-header">
      <span>{{ title }}</span>
    </h1>
    <br>
    <br>
    <br>
      <table class="table">
        <tr>
          <td>글번호</td>
          <td>제목 </td>
          <td>글쓴이</td>
          <td>작성날짜</td>
        </tr>
			{% for report in report_list %}
				<tr>
          <td>{{report.pk}}</td>
          <td class="post_title"><a href = '{% url "report:report_detail" company=report.board.company pk=report.pk %}'>{{report.title}}</a></td>
          <td>{{ report.author.first_name }}</td>
          <td>{{ report.created_at }}</td>
				</tr>
      {% endfor %}
    </table>
<nav class="text-left">
      <ul class="pagination">
      {% if report_list.has_previous %}
        <li>
          <a href="?page={{ report_list.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for page_number in report_list.paginator.page_range %}
        {% if page_number == report_list.number %}
          <li class="active"><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% else %}
        <li><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% endif %}
      {%endfor%}
      {% if report_list.has_next %}
        <li>
          <a href="?page={{ report_list.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% else %}
        <li class ="disabled">
          <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% endif %}
      </ul>
    </nav>
    <a style="margin-left:10px" href="{% url 'report:report_new' company=company %}">새 글쓰기</a>
    <!-- Pagination -->

   </div>
  {% endblock %}