Induk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('tax.urls', namespace = "tax")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^learning/', include('learning.urls', namespace="learning")),
    url(r'^report/', include('report.urls', namespace="report")),
    url(r'', include('notice.urls', namespace="notice")),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    # url(r'^accounts/register/$', UserCreateView.as_view(), name = 'register'),
    # url(r'^accounts/register/done/$', UserCreateDoneTV.as_view, name = 'register_done'),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views


urlpatterns = [
	url(r'^login/$', views.login, kwargs={'template_name': 'accounts/login.html'} ,name = 'login'),
	url(r'^signup/$', views.signup, name = 'signup'),
	url(r'^pw_reset/$', views.password_reset, name='password_reset'), # 직접 비밀번호 바꾸는 경우
	url(r'^pw_admin/$', views.password_reset_admin, name='password_reset_admin'), # 관리자가 비밀번호 리셋 시키는 경우
	# url(r'^register/$', UserCreateView.as_view(), name = 'register'),
    #url(r'^register/done/$', UserCreateDoneTV.as_view(), name = 'register_done'),
	#url(r'^logout/$', logout_page),
	url(r'^logout/$', logout, kwargs={'next_page': '/'}, name='logout'),
	url(r'^mypage/$', views.mypage, name='mypage'),
]

learning/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.learning_list, name = "learning_list"),
    url(r'^(?P<pk>\d+)/$', views.learning_detail, name="learning_detail"),
    url(r'^new/$', views.learning_new, name="learning_new"),
    url(r'^(?P<pk>\d+)/edit/$', views.learning_edit, name="learning_edit"),
    url(r'^(?P<pk>\d+)/del/$', views.learning_del, name="learning_del"),
    url(r'^(?P<pk>\d+)/comment/$', views.learning_comment, name="learning_comment"),
]

notice/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#	url(r'^$', views.index, name = 'notice.index'),
	url(r'^$', views.index, name = "index"),
	url(r'^main$', views.main, name = "main"),
    url(r'^notice/$', views.notice_list, name="notice_list"),
    url(r'^notice/(?P<pk>\d+)/$', views.notice_detail, name="notice_detail"),
    url(r'^notice/new/$', views.notice_new, name="notice_new"),
    url(r'^notice/(?P<pk>\d+)/edit/$', views.notice_edit, name="notice_edit"),
    url(r'^notice/(?P<pk>\d+)/del/$', views.notice_del, name="notice_del"),
    url(r'^notice/(?P<pk>\d+)/comment/$', views.notice_comment, name="notice_comment"),
]

report/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.report_index, name = 'report_index'),

	url(r'^(?P<company>\w+)/$', views.report_list, name="report_list"),
	url(r'^(?P<company>\w+)/new/$', views.report_new, name="report_new"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/$', views.report_detail, name="report_detail"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/edit/$', views.report_edit, name="report_edit"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/del/$', views.report_del, name="report_del"),
	url(r'^(?P<company>\w+)/(?P<pk>\d+)/comment/$', views.report_comment, name="report_comment"),
]

Induk/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block title %}仁德會計法人{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
    <!-- Bootstrap Core CSS -->
    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href='{% static "vendor/magnific-popup/magnific-popup.css" %}' rel="stylesheet">

    <!-- Theme CSS -->
    <link href='{% static "css/creative.min.css" %}' rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
{% block css%}
{% endblock %}
</head>

<body>

<div id="header">
    <!-- {% if user.is_active %}
<h4 class = "welcome">Welcome,
<strong>{% firstof user.get_short_name user.get_username %}</strong>
<a href="{% url 'accounts:logout' %}" > Logout</a>

</h4>
{% else %}
 -->{% block content %} {% endblock %}

        <!-- {% endif %} -->
</div>
{% block footer %} {% endblock %}

<!--Script Section START-->
<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
<script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!-- Theme JavaScript -->
<script src="{% static 'js/creative.min.js' %}"></script>
<!--Script Section END-->
</body>
</html>

Induk/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}仁德會計法人{% endblock %}</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />



<!-- Bootstrap Core CSS -->
    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href='{% static "vendor/magnific-popup/magnific-popup.css" %}' rel="stylesheet">

    <!-- Theme CSS -->
    <link href='{% static "css/creative.min2.css" %}' rel="stylesheet">
{% block css %}
{% endblock %}
</head>

<body id="page-top">
{% if messages %}
   {% for message in messages %}
     <div style="margin:0px" class="text-center alert alert-{{ message.tags }}">
       {{ message }}
     </div>
   {% endfor %}
 {% endif %}

    {% include 'navbar.html' %}

    <header></header>
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">2016 연말정산 TF</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                    <a href="{% url 'learning:learning_list' %}"><i class="fa fa-4x fa-diamond text-primary sr-icons"></i> </a>
                        <h3>Learning Materials</h3>
                        <p class="text-muted">학습자료</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'report:report_index' %}"><i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i></a>
                        <h3>Daily Report</h3>
                        <p class="text-muted">기업 상담 자료실</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'notice:notice_list' %}"><i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i></a>
                        <h3>Notice</h3>
                        <p class="text-muted">인덕회계법인 공지사항</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'questions:questions_list' %}"><i class="fa fa-4x fa-heart text-primary sr-icons"></i></a>
                        <h3>Questions</h3>
                        <p class="text-muted">질문게시판</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% block content %} {% endblock %}

    {% include 'footer.html' %}

        <!-- jQuery -->
    <script src='{% static "vendor/jquery/jquery.min.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src='{% static "vendor/scrollreveal/scrollreveal.min.js" %}'></script>
    <script src='{% static "vendor/magnific-popup/jquery.magnific-popup.min.js" %}'></script>

    <!-- Theme JavaScript -->
    <script src='{% static "js/creative.min.js" %}'></script>

    {% block javascript %}

    {% endblock %}

</body>

</html>

Induk/templates/base3.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}仁德會計法人{% endblock %}</title>


{% load staticfiles %}
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
<!-- Bootstrap Core CSS -->
    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href='{% static "vendor/magnific-popup/magnific-popup.css" %}' rel="stylesheet">

    <!-- Theme CSS -->
    <link href='{% static "css/creative.min2.css" %}' rel="stylesheet">
{% block css %}
{% endblock %}
</head>

<body id="page-top">

    {% include 'navbar.html' %}

    <header></header> 

    {% block content %} {% endblock %}

    {% include 'footer.html' %}

        <!-- jQuery -->
    <script src='{% static "vendor/jquery/jquery.min.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src='{% static "vendor/scrollreveal/scrollreveal.min.js" %}'></script>
    <script src='{% static "vendor/magnific-popup/jquery.magnific-popup.min.js" %}'></script>

    <!-- Theme JavaScript -->
    <script src='{% static "js/creative.min.js" %}'></script>

</body>

</html>

Induk/templates/base4.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        .alert-debug {
         background-color: #eeeeee;
         border-color: #eeeeee;
         color: #333;
        }
    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'assets/favicon/favicon.ico' %}">
    <title>仁德會計法人</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />

    <!-- CSS Plugins -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <!-- CSS Global -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,600,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/customized.css'%}">
    {% endblock %}

</head>
<body>

{% if messages %}
   {% for message in messages %}
     <div style="margin:0px" class="alert alert-{{ message.tags }}">
       {{ message }}
     </div>
   {% endfor %}
 {% endif %}
{% include "navbar.html" %}

{% block content %}
{% endblock %}

{% include "javascript.html" %}

{% block beforecustomjs %}
{% endblock %}
<!-- JS Custom -->
<script src="{% static 'js/custom.js' %}"></script>

{% block javascript %}
{% endblock %}

{% include "footer.html" %}
</body>
</html>

Induk/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>仁德會計法人</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />

    <!-- Bootstrap Core CSS -->
    <link href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href='{% static "vendor/magnific-popup/magnific-popup.css" %}' rel="stylesheet">

    <!-- Theme CSS -->
    <link href='{% static "css/creative.min.css" %}' rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    {% include 'navbar.html' %}
    <!--Content Section START-->
    <header>
        <div class="header-content">
	{% if messages %}
	   {% for message in messages %}
	     <div style="margin:0px" class="alert alert-{{ message.tags }}">
	       {{ message }}
	     </div>
	   {% endfor %}
	 {% endif %}
            <div class="header-content-inner">
                <h1 id="homeHeading">인덕회계법인 연말정산관리시스템</h1>
                <hr>
                <p>Year and tax adjustment</p>
                {% if user.is_active %}
                <a href="{% url 'notice:main' %}" class="btn btn-primary btn-xl page-scroll">Sign in</a>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-xl page-scroll">Sign in</a>
                {% endif %}
                <!--<a href="{% url 'accounts:login' %}"><i class="fa fa-lock"></i> <span class="hidden-md">Sign In</span></a> -->
            </div>
        </div>
    </header>
    <!--Content Section END-->

    <!-- jQuery -->
    <script src='{% static "vendor/jquery/jquery.min.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src='{% static "vendor/scrollreveal/scrollreveal.min.js" %}'></script>
    <script src='{% static "vendor/magnific-popup/jquery.magnific-popup.min.js" %}'></script>

    <!-- Theme JavaScript -->
    <script src='{% static "js/creative.min.js" %}'></script>
    {% include 'footer.html' %}
</body>

</html>

Induk/templates/javascript.html
{% load staticfiles %}
<!-- JS Global -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled and minified JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- JS Plugins -->
<script src="{% static 'assets/plugins/scrolltopcontrol/scrolltopcontrol.js' %}"></script>

Induk/templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>仁德會計法人</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.min2.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">
{% if messages %}
   {% for message in messages %}
     <div style="margin:0px" class="alert alert-{{ message.tags }}">
       {{ message }}
     </div>
   {% endfor %}
 {% endif %}

    {% include 'navbar.html' %}

    <header>
        </header>


    <!--Content Section START-->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">2016 연말정산 TF</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                    <a href="{% url 'learning:learning_list' %}"><i class="fa fa-4x fa-diamond text-primary sr-icons"></i> </a>
                        <h3>Learning Materials</h3>
                        <p class="text-muted">학습자료</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'report:report_index' %}"><i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i></a>
                        <h3>Daily Report</h3>
                        <p class="text-muted">기업 상담 자료실</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'notice:notice_list' %}"><i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i></a>
                        <h3>Notice</h3>
                        <p class="text-muted">인덕회계법인 공지사항</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'questions:questions_list' %}"><i class="fa fa-4x fa-heart text-primary sr-icons"></i></a>
                        <h3>Questions</h3>
                        <p class="text-muted">질문게시판</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Content Section END-->

    <!--Footer Section START-->
    {%  include 'footer.html' %}
    <!--Footer Section END-->

    <!--Script Section START-->
    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>
    <!--Script Section END-->

</body>

</html>

Induk/templates/navbar.html
{%load staticfiles %}

<!-- server git pull test -->

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                {% if user.is_authenticated %}
                    <a class="navbar-brand page-scroll" href="{% url 'notice:main' %}">仁德會計法人</a>
                {% else %}
                <a class="navbar-brand page-scroll" href="{% url 'notice:index' %}">仁德會計法人</a>
                {% endif %}
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}
                        <li>
                            <a class="page-scroll" href="{% url 'notice:main' %}">Menu</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'accounts:logout' %}?next={% url 'notice:index' %}">Logout</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="{% url 'accounts:mypage' %}">MY PAGE</a>
                        </li>
						<!-- <li>
							<a class="page-scroll" href="{% url 'accounts:password_reset' %}">비밀번호 변경</a>
						</li>
                        {% if user.is_staff %}
                            <li>
                                <a class="page-scroll" href="{% url 'accounts:password_reset_admin' %}">비밀번호 초기화</a>
                            </li>
                        {% endif %} -->
                     {% else %}
                         <!-- <li>
                             <a class="page-scroll" href="{% url 'accounts:login' %}">Login</a>
                         </li> -->
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>