Induk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^', include('tax.urls', namespace = "tax")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^learning/', include('learning.urls', namespace="learning")),
    url(r'^report/', include('report.urls', namespace="report")),
    url(r'', include('notice.urls', namespace="notice")),
    url(r'^questions/', include('questions.urls', namespace="questions")),
    # url(r'^accounts/', include('django.contrib.auth.urls')),
    # url(r'^accounts/register/$', UserCreateView.as_view(), name = 'register'),
    # url(r'^accounts/register/done/$', UserCreateDoneTV.as_view, name = 'register_done'),
]

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#	url(r'^$', views.index, name = 'notice.index'),
	url(r'^$', views.index, name = "index"),
	url(r'^main$', views.main, name = "main"),
    url(r'^notice/$', views.notice_list, name="notice_list"),
    url(r'^notice/(?P<pk>\d+)/$', views.notice_detail, name="notice_detail"),
    url(r'^notice/new/$', views.notice_new, name="notice_new"),
    url(r'^notice/(?P<pk>\d+)/edit/$', views.notice_edit, name="notice_edit"),
    url(r'^notice/(?P<pk>\d+)/del/$', views.notice_del, name="notice_del"),
    url(r'^notice/(?P<pk>\d+)/comment/$', views.notice_comment, name="notice_comment"),
]

notice/models.py
from django.db import models
from django.conf import settings
from model_rename import RenameFile


class Notice(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField(max_length=30)
	content = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	files = models.FileField(null=True, blank=True, upload_to=RenameFile('notice/%Y%m%d/'))
	image = models.ImageField(null=True, blank=True, upload_to=RenameFile('notice/%Y%m%d/'))
	show = models.BooleanField(default=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = '공지사항'
		verbose_name_plural = '공지사항'


class NoticeComment(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	message = models.TextField()
	notice = models.ForeignKey(Notice)
	# comment = models.ForeignKey("self", blank=True, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.notice.title

	class Meta:
		verbose_name = '공지사항 댓글'
		verbose_name_plural = '공지사항 댓글'

notice/forms.py
from django import forms
from .models import Notice, NoticeComment


class NoticeForm(forms.ModelForm):
	class Meta:
		model = Notice
		fields = ('title', 'content', 'files', 'image')


class NoticeCommentForm(forms.ModelForm):
	class Meta:
		model = NoticeComment
		fields = ('message',)

notice/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404

from .models import Notice, NoticeComment
from .forms import NoticeForm, NoticeCommentForm
from Induk.decorators import is_article_active

# def index(request):
# 	return render(request, "notice/index.html")


def index(request):
    if request.user.is_authenticated():
        return redirect('notice:main')
    return render(request, "index.html")


def main(request):
    if not request.user.is_authenticated():
        return redirect('notice:index')
    return render(request, 'main.html')


@login_required
def notice_list(request):
    notice_list = Notice.objects.filter(show=True).order_by("-updated_at")
    paginator = Paginator(notice_list, 10)

    page = request.GET.get('page')

    try:
        notice_list = paginator.page(page)
    except PageNotAnInteger:
        notice_list = paginator.page(1)
    except EmptyPage:
        notice_list = paginator.page(paginator.num_pages)

    return render(request, "notice/index.html", {
        "notice_list": notice_list,
    })


@login_required
@is_article_active
def notice_detail(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    return render(request, "notice/notice_detail.html", {
        "notice": notice,
        "comments": NoticeComment.objects.filter(notice=notice),
        "comment_form": NoticeCommentForm(),
    })


def notice_new(request):
    if request.method == "POST":
        form = NoticeForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.show = True
            form.save()
            return redirect("notice:notice_detail", form.pk)
    else:
        form = NoticeForm()
    return render(request, "notice/notice_form.html", {
        "form": form,
    })


@is_article_active
def notice_edit(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    if request.method == "POST":
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            form = form.save()
            return redirect("notice:notice_detail", notice.pk)
    else:
        form = NoticeForm(instance=notice)
    return render(request, "notice/notice_form.html", {
        "form": form,
    })


@is_article_active
def notice_del(request, pk):
    try:
        notice = Notice.objects.get(pk=pk)
    except Notice.DoesNotExist:
        return redirect('notice:notice_list')
    notice.show = False
    notice.save()

    return redirect('notice:notice_list')


@is_article_active
def notice_comment(request, pk):
    if request.method == 'POST':
        try:
            notice = Notice.objects.get(pk=pk)
        except Notice.DoesNotExist:
            return redirect('notice:notice_list')
        if not notice.show:
            return redirect('notice:notice_list')
        else:
            form = NoticeCommentForm(request.POST)
            if form.is_valid():
                print('form valid')
                comment = form.save(commit=False)
                comment.author = request.user
                comment.notice = notice
                comment.save()
            return render(request, "notice/notice_comment_form.html",{
                "notice": notice,
                "comments": NoticeComment.objects.filter(notice=notice),
                "comment_form": NoticeCommentForm(),
            })
    return redirect('notice:notice_list')

notice/templates/notice/index.html
{% extends 'base2.html' %}

{% block content %}

<div class="container">
    <h1 class="block-header">
      <span>공지사항</span>
    </h1>
      <table class="table">
        <tr>
          <td>글번호</td>
          <td>제목 </td>
          <td>글쓴이</td>
          <td>작성날짜</td>
        </tr>
{% for notice in notice_list %}
        <tr>
          <td>{{notice.pk}}</td>
          <td class="post_title"><a href = '{% url "notice:notice_detail" notice.pk %}'>{{notice.title}}</a></td>
          <td>{{ notice.author.first_name }}</td>
          <td>{{ notice.created_at }}</td>
        </tr>
      {% endfor %}
    </table>
<nav class="text-left">
      <ul class="pagination">
      {% if notice_list.has_previous %}
        <li>
          <a href="?page={{ notice_list.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for page_number in notice_list.paginator.page_range %}
        {% if page_number == notice_list.number %}
          <li class="active"><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% else %}
        <li><a href="?page={{page_number}}">{{page_number}}</a></li>
        {% endif %}
      {%endfor%}
      {% if notice_list.has_next %}
        <li>
          <a href="?page={{ notice_list.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% else %}
        <li class ="disabled">
          <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
      {% endif %}
      </ul>
    </nav>
    <a style="margin-left:10px" href = "{% url 'notice:notice_new' %}">새 글쓰기</a>
    <!-- Pagination -->

   </div>
  {% endblock %}

notice/templates/notice/notice_comment_form.html
{% load customtags %}

<div class="comments__new">
    <form name="comment_new" action="{% url 'notice:notice_comment' pk=notice.pk %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control" name="message" rows="1" placeholder="Write your comment here"></textarea>
        <button type="submit" id="comments__new" class="comments__new" class="btn btn-primary" value="SAVE">SAVE</button>
    </form>
</div>
<br/>
<div class="comments__list">
    <div class="comments__heading">{{ comments.count }} comments</div>
    <hr/> {% for comment in comments %}
    <div class="comments__item">
        <div class="comments--item__body">
            <div class="comments-item__info">
                <div class="comments-item-info__author">
                    {{ comment.author.first_name }}
                </div>
                <div class="comments-item-info__divider"><i class="fa fa-circle"></i></div>
                <div class="comments-item-info__timestamp">{{ comment.created_at|timesince|split:","|first }}전</div>
                <div class="comments-item__content">{{ comment.message }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

notice/templates/notice/notice_detail.html
{% extends 'base4.html' %}
{% load customtags %}
{% load staticfiles %}
{% block css %}
<style>
.title_{
    font-size:20px;
}
.author_{
    color:gray;
}
.time_recorded{
    color:gray;
}
.content_{
    margin-top:40px;
    margin-left:5%;
    margin-right:5%;
    font-size:20px;
}
.edit_del{
    margin-right:5%;
}
.comment_body{
margin:1%;
}
button[type=submit]{
  margin:1%;
  float:right;
  color:white;
  padding:5px 15px;
  background:orange;
  border:0 none;
  cursor:pointer;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
</style>
{% endblock %}

{% block content %}

 <div class="page-topbar">
      <div class="container">
        <div class="row">
          <div class="col-sm-4">

            <h3>공지 사항</h3>

          </div>
          <div class="col-sm-8 hidden-xs">

            <ol class="breadcrumb">
              <li><a href="{% url 'notice:index' %}">Home</a></li>
              <li><a href="{% url 'notice:notice_list' %}"> 리스트 보기 </a></li>
              <li class="active">{{notice.title}}</li>
            </ol>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </div>

<div class = "container">
  <div class="row">
    <div class="col-sm-12">
      <div class="bolg__item">
        <div class="blog__header">
          <h1 class="blog__title">
            {{ notice.title }}
          </h1>
          <ul class="blog__info">
            <li><i class="fa fa-user"></i>&nbsp;{{ notice.author.first_name }}</li>
            <li><i class="fa fa-calendar"></i>&nbsp;{{ notice.created_at}}</li>
            <li><a href="/notice" style="color:white; background-color:orange;" class="btn btn-xs">List</a></li>
            {% if request.user == notice.author %}
              <li><a href="{% url 'notice:notice_edit' notice.pk %}" style="color:white; background-color: orange;" class="btn btn-xs">edit</a></li>
              <li><a href="{% url 'notice:notice_del' notice.pk %}" style="color:white; background-color:orange;" class="btn btn-xs">delete</a></li>
            {% endif %}
          </ul>
        </div>
        <div class="blog__body">
          <p>
            {{ notice.content|linebreaks }}
          </p>
        </div>

         {% if notice.files %}
          files : {{notice.files.url|split:"/"|last }} <br/>
          <a download="{{notice.files.url}}" href="{{notice.files.url}}">파일 다운로드 받기</a><br>
        {% endif %}

        {% if notice.image %}
          images : <img src="{{ notice.image.url }}" class="img-responsive" style="max-width: 50%"> <br/>
          <a download="{{notice.image.url}}" href="{{notice.image.url}}">이미지 다운로드 받기</a>
        {% endif %}
        <br/><br/>
      </div>
      <div class="comments">
      {% include 'notice/notice_comment_form.html' %}
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block javascript %}
<script>
var js_root = "{% static 'js/comment_add.js'%}"
</script>
<script src="{% static 'js/comment_add.js' %}"></script>
{% endblock %}

notice/templates/notice/notice_form.html
{% extends 'base2.html' %}
{% load bootstrap3 %}

{% block content %}
<div class = "container">
<h1 class = "block-header">
<span> 공지사항 </span>
</h1>
<br>
<br>

<div class = "container">
<div class = "col-sm-12">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">SAVE</button>
</form>
</div>
</div>
</div>
{% endblock %}